name: build rpm
on: [push, pullrequest]
jobs:
  steps:
    - name: init
      run: gem install package_cloud
    
    - name: build
      run: echo make rpm

    - name: publish
      run: package_cloud push tizitomm/cardano cardano-node.rpm