name: build rpm
on: [push]
jobs:
  BuildRPM:
    runs-on: ubuntu-latest
    container: rockylinux:latest
    steps:
      - name: build
        run: | 
          gem install package_cloud
          echo make rpm
          package_cloud push tizitomm/cardano cardano-node.rpm